[package]
name = "fileslice"
version = "0.1.0"
edition = "2021"
license = "Unlicense"

[dependencies]
# Chrono is not a direct dependency; it's a dependency of "parquet".  However,
# parquet's Cargo.toml is slightly buggy, so if we don't specify chrono here
# then parquet fails to compile.
chrono = { version = "0.4.19", default-features = false, features = ["clock"], optional = true }
parquet = { version = "15.0.0", default-features = false, optional = true }
tar = { version = "0.4.38", optional = true }

[features]
default = ["parquet", "tar"]
parquet = ["dep:parquet", "chrono"]

[dev-dependencies]
parquet = { version = "15.0.0", features = ["zstd"], default-features = false }
