[package]
name = "fileslice"
description = "Slices of files"
version = "0.2.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2021"
license = "Unlicense"
repository = "https://github.com/asayers/fileslice"

[dependencies]
parquet = { version = "27.0.0", default-features = false, optional = true }
tar = { version = "0.4.38", optional = true }

[features]
default = ["parquet", "tar"]

[dev-dependencies]
parquet = { version = "27.0.0", features = ["zstd"], default-features = false }
